### ISSUE TITLE
timestamp as time object

### ISSUE THREAD

**Issue by erwiese** [logdyhq/logdy-core#40]
Curently the timestamp seems to be just text. This means no possibility to filter for time ranges.
Something like `time >= 2024-07-11T00:00:00Z AND time <= 2024-07-12T00:00:00Z` would be helpfull.

Cheers

**Comment by PeterOsinski** [comment]
@erwiese this is now possible with recent `0.14` release! You can now filter by time.
Take a look at the [docs](https://logdy.dev/docs/explanation/facets#date-and-time-filtering).

<img src="https://logdy.dev/releases/v0_14/feat-timepicker.png" width=50% height=50%>

**Comment by erwiese** [comment]
:+1:
