### ISSUE TITLE
Feature Request: docker image

### ISSUE THREAD

**Issue by azertylr** [logdyhq/logdy-core#52]
Hello,

It would be great to have a docker image for this fantastic tool :)

It would make it easier to deploy

Best

**Comment by azertylr** [comment]
Hi @PeterOsinski 

Docker allows an easy deployment and flexibility if you need several instances of lodgy. You can for example add directly to the docker compose of the project a container with logdy. It also provides an isolation and a flexible management when you have all of your app running with docker.

I did create a container for testing and it works well, and add it to my docker compose :

```yaml
services:
  caddy:
   ...

  logdy:
    image: logdy
    container_name: logdy
    read_only: true
    volumes:
      - /home/docker/caddy/logs/access.log:/var/log/access.log:ro
      - /home/docker/caddy/logs/error.log:/var/log/error.log:ro
      - /home/docker/logdy:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    command: ["./logdy", "--ui-ip", "0.0.0.0", "--config", "/config/logdy.json", "follow", "/var/log"]

**Comment by azertylr** [comment]
and a very simple dockerfile

```yaml
FROM alpine:latest

ENV LOGDY_VERSION=0.13.0

ADD "https://github.com/logdyhq/logdy-core/releases/download/v${LOGDY_VERSION}/logdy_linux_amd64" /usr/local/bin/logdy

RUN chmod +x /usr/local/bin/logdy

ENTRYPOINT ["/usr/local/bin/logdy"]

CMD ["--ui-ip", "0.0.0.0", "--config", "/config/logdy.json", "follow", "/var/log"]

**Comment by azertylr** [comment]
Thanks, I can help for testing and implementing!

**Comment by azertylr** [comment]
Hi,
I did a test here: https://github.com/azertylr/logdy-docker/

**Comment by pataquets** [comment]
@PeterOsinski Just submitted #56. `Dockerfile` tries to be as much generic and unopinionated as possible, to serve as many usage scenarios as possible (e.g. not size-optimized, yet).
It will work for @azertylr's `docker-compose.yml` scenario, although the service will need a `command` key for passing the command switches and a more detailed `build` section to point to the `Dockerfile` Github repo URL.
Everyone's welcomed to take it for a spin and provide feedback on the PR.

**Comment by pataquets** [comment]
@azertylr: now that #56 is merged, you might want to tweak your Compose manifest by adding a `build` section which references this repo's URL and see if it works for you.
See [Compose Build Specification](https://docs.docker.com/reference/compose-file/build/) for how to make a service build from a repo URL.

**Comment by azertylr** [comment]
Hello,

It is working great :) my docker-compose:

Thanks! 

````yaml
services:
  logdy:
    build: https://github.com/logdyhq/logdy-core.git
    container_name: logdy
    read_only: true
    volumes:
      - /home/docker/caddy/logs:/var/log:ro
      - /home/docker/logdy/logdy_caddy2.json:/config/logdy.json
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

**Comment by azertylr** [comment]
Just something I've just noticed, image is 935.6 MB, versus 87 MB for the exe file :(

**Comment by borosr** [comment]
> Just something I've just noticed, image is 935.6 MB, versus 87 MB for the exe file :(

It is happening because the dockerfile's base image is the `golang:1` and this is a big one, i'll try my best to sumbit a pr today with a multistep docker build that reduces the image size.

**Comment by pataquets** [comment]
@azertylr : Glad to know it's working for you and thanks for sharing your Docker Compose snippet. I think it'll make for a good usage example, once Docker usage it's settled. As you noticed, size was not a priority initially and I don't think should be yet.

@borosr : A size optimization would be a desirable improvement down the road and much appreciated, indeed. But there are a few follow-up improvements which might come later that I think would be easier without the size improvements, to come later.
For the full context and rationale of the Dockerfile check out #56. Even better, if you have any feedback, I think that perhaps there will be a better place to discuss the Docker image implementation details and maybe spin off relevant issues.

@PeterOsinski : Also, to properly scope the Docker efforts from here on, I'd like to know your stance as maintainer on how much you're up to add to the project in terms of future maintenance. Do you prefer keeping it as minimal as possible (ie. just a canonical "just builds :tm:, you figure out usage"  `Dockerfile` in repo, no built public image) or do you want to fully support Docker usage (public image, docs, etc.)?
Needless to say, there's no right answer, as it depends entirely on how much time and effort you feel like to commit to this specific feature in the future.

**Comment by obriat** [comment]
If I understand it correctly the logdy only input is still throught tcp port?
In docker mode it could also listen to other containers stdout/stderr output, just like https://dozzle.dev/ do.
This way one could embed a log watcher/parser into its docker compose stack
