### ISSUE TITLE
Crash in demo when trying to search using regex character class

### ISSUE THREAD

**Issue by deinspanjer** [logdyhq/logdy-core#57]
I was pretty impressed with the UX of your demo app at https://demo.logdy.dev/ but when I tried to enter a few different searches, I hit a crash bug.

If you try to make a character class expression such as `s[ha]d`, it will crash as soon as it starts evaluating the expression.
That seems to be after the search box has more than three characters in it, so it will crash as soon as you type the `h`.
If you start with the character class brackets `[]` and then put the `ha` inside it and the s in front of it, it won't crash because it doesn't ever have an invalid regex string.

**Comment by PeterOsinski** [comment]
This has been fixed in 0.13.2, thanks for contribution!
