### ISSUE TITLE
InitializeLogdy should return the servemux, not accept it

### ISSUE THREAD

**Issue by CAFxX** [logdyhq/logdy-core#60]
There is currently no way to initialize logdy before the mux is created. When logdy is embedded in existing applications, it is not a given that the servemux is created before everything else: important logic (that requires logging infrastructure to be already up and running, e.g. loading configuration data, opening/testing database connections, loading/initializing static data or caches) can and does run before the servemux creation. If InitializeLogdy returned the servemux, logdy could be initialized ahead of time, solving the "logging before servemux exists" requirement, and then when the application servemux is ready the logdy servemux could be easily added to it.

**Comment by PeterOsinski** [comment]
I'll close this one as it seems it solves the issue
