### ISSUE TITLE
0.13.3 release build issue

### ISSUE THREAD

**Issue by chenrui333** [logdyhq/logdy-core#68]
👋 looks like with [this commit](https://github.com/logdyhq/logdy-core/commit/af944c5b31f60918adf7b33eacdfff77c2ab0203), now the build is going forever for [homebrew CI](https://github.com/Homebrew/homebrew-core/pull/200730), probably should revert it.

**Comment by PeterOsinski** [comment]
Hi @chenrui333, I analyzed the build process of the formulae. It was hanging during completions generation as the webserver was starting for that command therefore `logdy completion bash` never exited. I fixed it in [commit](https://github.com/logdyhq/logdy-core/commit/c6b2b893d4f3980c9f8636e511a9ecab7e591008). How do we proceed with removing the patch from formulae file?

**Comment by chenrui333** [comment]
@PeterOsinski in that case, can you cut a new release? we can remove the patch from there. thanks!
